services:
  gutenberg-lab:
    image: wordcracker-textlab
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/workspace/notebooks
      - ./scripts:/workspace/scripts
      - ./data:/workspace/data
      - ./raw_books:/workspace/raw_books
      - /data/books:/workspace/books
      - /data/clean_books:/workspace/clean_books
      - /data/chroma_db:/workspace/chroma_db
      - /data/spgc:/workspace/spgc
      - /data/wodehouse_raw:/workspace/wodehouse_raw
      - /data/gutenberg_raw:/workspace/gutenberg_raw
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: >
      sh -c "jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root
      --ServerApp.token='' --ServerApp.password=''
      --notebook-dir=/workspace"
